### ISSUE TITLE
Grafana explorer doesn't load log volume past 116 days and throwing errors related to loki

### ISSUE THREAD

**Issue by Skipper0707** [metrico/qryn#181]
Hello again;

When I set the time range more than 116 days in the Grafana explorer ( either past 116 days or any range more than 116 days ), it fails to load the log volume and throws the following error:

![image](https://user-images.githubusercontent.com/71173136/178255180-b6389225-5993-4d17-aeca-7c08b9c78a81.png)

**Please note that** the log entries themselves get loaded just fine meaning I can see the logs and their detail but the log volume won't load.

When I check the `grafana-server` logs the following errors can be seen:

```bash
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-11T08:17:25.613322771Z level=error msg="Request error" error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:221 (0x44e026)
/usr/local/go/src/runtime/signal_unix.go:735 (0x44dff6)
/drone/src/pkg/tsdb/loki/api.go:166 (0x26ed67d)
/drone/src/pkg/tsdb/loki/loki.go:212 (0x26f3332)
/drone/src/pkg/tsdb/loki/loki.go:195 (0x26f307b)
/drone/src/pkg/tsdb/loki/loki.go:174 (0x26f26ea)
/drone/src/pkg/plugins/backendplugin/coreplugin/core_plugin.go:81 (0x275cf90)
/drone/src/pkg/plugins/plugins.go:247 (0x10ed88d)
/drone/src/pkg/plugins/manager/client.go:22 (0x2765b11)
/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:38 (0x2765577)
/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:67 (0x2765878)
/drone/src/pkg/plugins/manager/client.go:21 (0x27657a9)
/drone/src/pkg/services/query/query.go:165 (0x1d96efb)
/drone/src/pkg/services/query/query.go:81 (0x1d96296)
/drone/src/pkg/api/metrics.go:48 (0x20c19bb)
/drone/src/pkg/api/routing/routing.go:17 (0x181c8e1)
/drone/src/pkg/api/response/web_hack.go:39 (0x10ea272)
/usr/local/go/src/reflect/value.go:556 (0x4e1964)
/usr/local/go/src/reflect/value.go:339 (0x4e0ee4)
/drone/src/pkg/web/inject.go:159 (0xf578a6)
/drone/src/pkg/web/inject.go:119 (0xf574f4)
/drone/src/pkg/web/context.go:71 (0xf5678b)
/drone/src/pkg/web/context.go:66 (0xf5e5da)
/drone/src/pkg/web/macaron.go:141 (0xf5e5cc)
/usr/local/go/src/net/http/server.go:2047 (0x6d5bee)
/drone/src/pkg/middleware/csp.go:22 (0x1813972)
/usr/local/go/src/reflect/value.go:556 (0x4e1964)
/usr/local/go/src/reflect/value.go:339 (0x4e0ee4)
/drone/src/pkg/web/inject.go:159 (0xf578a6)
/drone/src/pkg/web/inject.go:119 (0xf574f4)
/drone/src/pkg/web/context.go:71 (0xf5678b)
/drone/src/pkg/web/context.go:66 (0xf5e5da)
/drone/src/pkg/web/macaron.go:141 (0xf5e5cc)
/usr/local/go/src/net/http/server.go:2047 (0x6d5bee)
/drone/src/pkg/web/render.go:44 (0xf59386)
/usr/local/go/src/reflect/value.go:556 (0x4e1964)
/usr/local/go/src/reflect/value.go:339 (0x4e0ee4)
/drone/src/pkg/web/inject.go:159 (0xf578a6)
/drone/src/pkg/web/inject.go:119 (0xf574f4)
/drone/src/pkg/web/context.go:71 (0xf5678b)
/drone/src/pkg/web/context.go:66 (0xf5e5da)
/drone/src/pkg/web/macaron.go:141 (0xf5e5cc)
/usr/local/go/src/net/http/server.go:2047 (0x6d5bee)
/drone/src/pkg/middleware/csrf.go:47 (0x1813f6a)
/usr/local/go/src/reflect/value.go:556 (0x4e1964)
/usr/local/go/src/reflect/value.go:339 (0x4e0ee4)
/drone/src/pkg/web/inject.go:159 (0xf578a6)
/drone/src/pkg/web/inject.go:119 (0xf574f4)
/drone/src/pkg/web/context.go:71 (0xf5678b)
/drone/src/pkg/web/context.go:66 (0x1816eca)
/drone/src/pkg/middleware/recovery.go:168 (0x1816ec1)
/drone/src/pkg/api/response/web_hack.go:51 (0x10ea0d3)
/usr/local/go/src/reflect/value.go:556 (0x4e1964)
/usr/local/go/src/reflect/value.go:339 (0x4e0ee4)
/drone/src/pkg/web/inject.go:159 (0xf578a6)
/drone/src/pkg/web/inject.go:119 (0xf574f4)
/drone/src/pkg/web/context.go:71 (0xf5678b)
/drone/src/pkg/web/context.go:66 (0x1814a44)
/drone/src/pkg/middleware/logger.go:35 (0x1814a30)
/drone/src/pkg/api/response/web_hack.go:31 (0x10ea434)
/usr/local/go/src/reflect/value.go:556 (0x4e1964)
/usr/local/go/src/reflect/value.go:339 (0x4e0ee4)
/drone/src/pkg/web/inject.go:159 (0xf578a6)
/drone/src/pkg/web/inject.go:119 (0xf574f4)
/drone/src/pkg/web/context.go:71 (0xf5678b)
/drone/src/pkg/web/context.go:66 (0x1817b59)
/drone/src/pkg/middleware/request_metrics.go:58 (0x1817b48)
/drone/src/pkg/api/response/web_hack.go:31 (0x10ea434)
/usr/local/go/src/reflect/value.go:556 (0x4e1964)
/usr/local/go/src/reflect/value.go:339 (0x4e0ee4)
/drone/src/pkg/web/inject.go:159 (0xf578a6)
/drone/src/pkg/web/inject.go:119 (0xf574f4)
/drone/src/pkg/web/context.go:71 (0xf5678b)
/drone/src/pkg/web/context.go:66 (0x1819359)
/drone/src/pkg/middleware/request_tracing.go:81 (0x1819348)
/drone/src/pkg/api/response/web_hack.go:31 (0x10ea434)
/usr/local/go/src/reflect/value.go:556 (0x4e1964)

/usr/local/go/src/reflect/value.go:339 (0x4e0ee4)
/drone/src/pkg/web/inject.go:159 (0xf578a6)
/drone/src/pkg/web/inject.go:119 (0xf574f4)
/drone/src/pkg/web/context.go:71 (0xf5678b)
/drone/src/pkg/web/router.go:156 (0xf5abfd)
/drone/src/pkg/web/router.go:213 (0xf5b8b5)
/drone/src/pkg/web/macaron.go:176 (0xf58cd0)
/usr/local/go/src/net/http/server.go:2879 (0x6d915a)
/usr/local/go/src/net/http/server.go:1930 (0x6d4cc7)
/usr/local/go/src/runtime/asm_amd64.s:1581 (0x46c080)

logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-11T08:17:25.613411017Z level=error msg="Request Completed" method=POST path=/api/ds/query status=500 remote_addr=<SOME_IP> time_ms=136 duration=136.692871ms size=123 referer="http://<SOME_IP>:<SOME_PORT>/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bappname%3D%5C%22LOG%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now%2Fy%22,%22to%22:%22now%2Fy%22%7D%7D" traceID=00000000000000000000000000000000⏎
```

Any ideas about this?

Thanks in advance.

**Comment by akvlad** [comment]
@Skipper0707 log volume for 116 days may be too big to count in qryn server in 30 seconds.
You can try increasing timeouts in the grafana datasource configurations page. 
But anyway according to my last benchmarks an OK clickhouse server can process 30-40mil log rows / second. So if you have 1billion rows written during 116 days it needs 34 seconds to compute the volume.
---
Please make sure that you have the latest version of qryn. We fixed some problems about the volume information in Grafana 9 about a week ago.

**Comment by Skipper0707** [comment]
I do have the latest version of `qryn`.

Unfortunately increasing the timeout to 60 seconds didn't work and the error still persists, is it safe to assume there is something wrong with the `clickhouse` or its configurations?

I've optimized my `clickhouse` in order to reduce memory and CPU usage.

I will retry with default configurations to see if it has any effects.

**Comment by Skipper0707** [comment]
@akvlad I just retried with clickhouse's default configurations meaning no optimization and the same error happens.

so far neither the timeout nor the clickhouse no-optimization seems to have solved the problem.

Can you please tell me what an OK clickhouse is? Are there any specific configurations or optimizations I should be doing since I'm using `qryn`?

**Comment by Skipper0707** [comment]
I sure will try that, thanks for the tip.

**Comment by Skipper0707** [comment]
@akvlad I tried what you asked and `qryn` completed all the requests that were wrapped to `rate(....)` without any problems, as a matter of fact, the bars and everything were there.

I also tried a `rate({appname:"app"}[1m]` with the range of 180 days and that worked fine too.

So I guess this is on Grafana.

Thanks for your help.

**Comment by akvlad** [comment]
The log volume is a quite new feature. It can have flaws.

**Comment by lmangani** [comment]
@Skipper0707 can you set DEBUG mode on temporarily and catch the problem logql query grafana sends? 
It might differ and/or have changed possibly
